name: Release

permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  upload-assets:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: bing-client
          tar: unix
          zip: windows
          token: ${{ secrets.GITHUB_TOKEN }}